//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingWPFDesktopVersion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=F:\\Resoneuronance\\Banking\\BankingWPFDesktopVersion\\BankingWPFDesktopV" +
            "ersion\\bin\\Debug\\banking.sqlite")]
        public string bankingConnectionString {
            get {
                return ((string)(this["bankingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=bankingsqlite;database=C:\\Users\\ANAND\\Documents\\Visual Studio 2010\\Projects\\B" +
            "ankingWPFDesktopVersion\\BankingWPFDesktopVersion\\bin\\Debug\\banking.sqlite;stepap" +
            "i=0;notxn=0;shortnames=0;longnames=0;nocreat=0;nowchar=0;fksupport=1;oemcp=0;big" +
            "int=0;jdconv=0")]
        public string C__Users_ANAND_Documents_Visual_Studio_2010_Projects_BankingWPFDesktopVersion_BankingWPFDesktopVersion_bin_Debug_banking_sqliteConnectionString {
            get {
                return ((string)(this["C__Users_ANAND_Documents_Visual_Studio_2010_Projects_BankingWPFDesktopVersion_Ban" +
                    "kingWPFDesktopVersion_bin_Debug_banking_sqliteConnectionString"]));
            }
        }
    }
}
