using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Data;

namespace BankingWPFDesktopVersion
{
    /// <summary>
    /// Interaction logic for Accounts.xaml
    /// </summary>
    public partial class Transactions : Page
    {
        private DataTable account;
        private DataTable customer;
        private DataTable transactions;
        private DataController dc;
        public static string MARATHI_FONT = "Shivaji02";
        public Transactions(DataTable account)
        {
            InitializeComponent();
            //this.accountNumber = dataset.account.account_noColumn.ToString();
            this.account = account;
            dc = new DataController();
            this.customer = dc.getCustomer(account.Rows[0]["customer_id"].ToString());
            this.transactions = dc.getTransactions(account.Rows[0]["account_no"].ToString());
            //gridAccounts.ItemsSource = new DataController().getCustomer(accountNumber).DefaultView;
            lblCustomerNameLoaded.Content = customer.Rows[0]["customer_name"];
            lblBalance.Content = account.Rows[0]["closing_balance"];
            customizeGrid();
            customizeControls();

        }

        private void customizeControls()
        {
            lblCustomerName.Content = "नाव";
            lblAccBalance.Content = "शिल्लक";
            button1.Content = "अहवाल निर्माण";
            lblCustomerNameLoaded.FontFamily = new FontFamily(MARATHI_FONT);
            lblCustomerNameLoaded.FontSize = 18;
            lblBalance.FontFamily = new FontFamily(MARATHI_FONT);
            lblBalance.FontSize = 18;
        }

        private void dataGrid1_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            
        }

        private void customizeGrid()
        {
            gridTransactions.ItemsSource = transactions.DefaultView;
            gridTransactions.AutoGenerateColumns = true;
            //gridTransactions.AutoGeneratedColumns = 
           
        }

        private void Page_Loaded(object sender, RoutedEventArgs e)
        {

        }

        private void gridTransactions_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //MessageBox.Show(gridTransactions.Columns.Count.ToString());
            gridTransactions.Columns[0].Visibility = Visibility.Hidden;
            gridTransactions.Columns[1].Header = "व्यवहार";
            gridTransactions.Columns[2].Header = "तारीख";
            gridTransactions.Columns[3].Header = "जमा तारीख";
            gridTransactions.Columns[4].Header = "नकद";
            gridTransactions.Columns[5].Header = "स्पष्टीकरण";
            gridTransactions.Columns[6].Header = "चेक क्र.";
            gridTransactions.Columns[7].Header = "खाते क्र.";
        }

        private void button1_Click(object sender, RoutedEventArgs e)
        {
            Reports report = new Reports(dc.getAllTransactionsForAccount(account.Rows[0]["account_no"].ToString()), "TransactionsReport");
            this.NavigationService.Navigate(report);
        }
    }
}
